lesite/models/__init__.py
from .db import db
from .user import User
from .token import Token
from .client import Client
from .authorization_code import AuthorizationCode

lesite/models/authorization_code.py
from .db import db
from lesite.utilities import str_uuid4
from authlib.integrations.sqla_oauth2 import OAuth2AuthorizationCodeMixin

class AuthorizationCode(db.Model, OAuth2AuthorizationCodeMixin):
    id = db.Column(db.String(64), primary_key=True, default=str_uuid4())
    user_id = db.Column(
        db.String(64), db.ForeignKey("users.id", ondelete="CASCADE"))
    user = db.relationship("User")

lesite/models/client.py
from lesite.models import db
from lesite.utilities import str_uuid4
from authlib.integrations.sqla_oauth2 import OAuth2ClientMixin

class Client(db.Model, OAuth2ClientMixin):
    __tablename__ = "oauth2_clients"

    id = db.Column(db.String(64), primary_key=True, default=str_uuid4())
    user_id = db.Column(
        db.String(64), db.ForeignKey("users.id", ondelete="CASCADE"))
    user = db.relationship("User")

lesite/models/db.py
from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()


def setup_db(app):
    @app.before_first_request
    def init_db():
        db.create_all()

    db.init_app(app)

lesite/models/token.py
from lesite.models import db
from lesite.utilities import str_uuid4
from authlib.integrations.sqla_oauth2 import OAuth2TokenMixin

class Token(db.Model, OAuth2TokenMixin):
    __tablename__ = "oauth2_tokens"

    id = db.Column(db.String(64), primary_key=True, default=str_uuid4())
    user_id = db.Column(
        db.String(64), db.ForeignKey("users.id", ondelete="CASCADE"))
    user = db.relationship("User")

lesite/models/user.py
from lesite.models import db
from flask_login import UserMixin
from lesite.utilities import str_uuid4

class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.String(64), primary_key=True, default=str_uuid4())
    username = db.Column(db.String(40), unique=True)

    def get_user_id(self):
        return self.id

    def check_password(self, password):
        return password == "valid"

    def __str__(self):
        return "User<id={}, username={}>".format(self.id, self.username)

lesite/app.py
from flask import Flask
from lesite.models.db import setup_db
from lesite.auth import authbp as auth_blueprint
from lesite.index import indexbp as index_blueprint
from lesite.oauth2_server import setup_oauth2_server
from lesite.login_manager import setup_login_manager
from lesite.oauth2 import oauth2bp as oauth2_blueprint

def create_app(config=None):
    app = Flask(__name__)
    if config is not None:
        if isinstance(config, dict):
            app.config.update(config)
        elif config.endswith(".py"):
            app.config.from_pyfile(config)

    setup_config(app)
    setup_blueprints(app)
    return app

def setup_config(app):
    setup_db(app)
    setup_login_manager(app)
    setup_oauth2_server(app)

def setup_blueprints(app):
    app.register_blueprint(index_blueprint, url_prefix="")
    app.register_blueprint(auth_blueprint, url_prefix="/auth")
    app.register_blueprint(oauth2_blueprint, url_prefix="/oauth")

lesite/index/__init__.py
from flask import Blueprint

indexbp = Blueprint("index", __name__)
from . import routes

lesite/index/routes.py
import datetime
from lesite.index import indexbp
from lesite.models import db, Client
from flask_login import current_user
from lesite.utilities import split_by_crlf
from lesite.oauth2_server import require_oauth
from authlib.integrations.flask_oauth2 import current_token
from authlib.common.security import generate_token
from flask import request, jsonify, redirect, url_for, render_template

@indexbp.route("/", methods=["GET"])
def index():
    clients = []
    user = None
    if current_user.is_authenticated:
        clients = Client.query.filter_by(user_id=current_user.id).all()
        user = current_user
        pass
    return render_template("index.html", user=user, clients=clients)

@indexbp.route("/add_client", methods=("GET", "POST"))
def add_client():
    if not current_user.is_authenticated:
        return redirect(url_for("index.index"))
    if request.method == "GET":
        return render_template("add_client.html")
    form = request.form
    client = Client()
    client.user_id=current_user.get_user_id()
    client.client_id = generate_token(24)
    client.client_id_issued_at = datetime.datetime.now().timestamp()
    client.client_secret = ""
    if client.token_endpoint_auth_method != "none":
        client.client_secret = generate_token(48)

    client_metadata = {
        "client_name": form["client_name"],
        "client_uri": form["client_uri"],
        "grant_types": split_by_crlf(form["grant_type"]),
        "redirect_uris": split_by_crlf(form["redirect_uri"]),
        "response_types": split_by_crlf(form["response_type"]),
        "scope": form["scope"],
        "token_endpoint_auth_method": form["token_endpoint_auth_method"]
    }
    client.set_client_metadata(client_metadata)
    db.session.add(client)
    db.session.commit()
    return redirect("/")

@indexbp.route("/api/profile")
@require_oauth("openid profile")
def profile():
    user = current_token.user
    return jsonify(id=user.id, username=user.username)

lesite/oauth2/__init__.py
from flask import Blueprint

oauth2bp = Blueprint("oauth2", __name__)
from . import routes

lesite/oauth2/routes.py
from lesite.oauth2 import oauth2bp
from flask_login import current_user
from lesite.utilities import get_host
from flask import request, url_for, redirect, render_template
from lesite.oauth2_server import (
    server,
    RevocationEndpoint,
    IntrospectionEndpoint)

@oauth2bp.route("/authorize", methods=("GET", "POST"))
def authorize():
    if current_user.is_anonymous:
        next_url="{}{}".format(
            get_host(request),
            url_for(
                "oauth2.authorize",
                client_id=request.args.get("client_id"),
                scope=request.args.get("scope"),
                response_type=request.args.get("response_type"),
                nonce=request.args.get("nonce"),
                redirect_uri=request.args.get("redirect_uri")))
        return redirect(url_for("auth.login", next_url=next_url))
    if request.method == "GET":
        grant = server.validate_consent_request(end_user=current_user)
        return render_template(
            "authorization.html", grant=grant, user=current_user)
    confirmed = request.form["confirm"]
    if confirmed:
        # Granted by the resource owner
        return server.create_authorization_response(grant_user=current_user)
    # denied by resource owner
    return server.create_authorization_response(grant_user=None)

@oauth2bp.route("/token", methods=["POST"])
def token():
    return server.create_token_response()

@oauth2bp.route("/revoke", methods=["POST"])
def revoke_token():
    return server.create_endpoint_response(RevocationEndpoint.ENDPOINT_NAME)

@oauth2bp.route("/introspect", methods=["POST"])
def introspect_token():
    return server.create_endpoint_response(InstrospectionEndpoint.ENDPOINT_NAME)

lesite/oauth2_grants/__init__.py
from functools import wraps
from .openid_code import OpenIDCode
from .password_grant import PasswordGrant
from .refresh_token_grant import RefreshTokenGrant
from .openid_hybrid_grant import OpenIDHybridGrant
from .openid_implicit_grant import OpenIDImplicitGrant
from .authorization_code_grant import AuthorizationCodeGrant
from .grant_utilities import exists_nonce, get_jwt_config, generate_user_info

def attach_methods(cls):
    functions = [exists_nonce, get_jwt_config, generate_user_info]
    for func in functions:
        setattr(cls, func.__name__, func)

openid_flow_classes = [OpenIDCode, OpenIDImplicitGrant, OpenIDHybridGrant]
for cls in openid_flow_classes:
    attach_methods(cls)

lesite/templates/add_client.html
<style>
  label, label > span { display: block; }
  label { margin: 15px 0; }
</style>

<a href="/">Home</a>

<form action="{{url_for('index.add_client')}}" method="post">
  <label>
    <span>Client Name</span>
    <input type="text" name="client_name">
  </label>
  <label>
    <span>Client URI</span>
    <input type="url" name="client_uri">
  </label>
  <label>
    <span>Allowed Scope</span>
    <input type="text" name="scope">
  </label>
  <label>
    <span>Redirect URIs</span>
    <textarea name="redirect_uri" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Allowed Grant Types</span>
    <textarea name="grant_type" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Allowed Response Types</span>
    <textarea name="response_type" cols="30" rows="10"></textarea>
  </label>
  <label>
    <span>Token Endpoint Auth Method</span>
    <select name="token_endpoint_auth_method">
      <option value="client_secret_basic">client_secret_basic</option>
      <option value="client_secret_post">client_secret_post</option>
      <option value="none">none</option>
    </select>
  </label>
  <button>Submit</button>
</form>

lesite/templates/authorization.html
<p>{{grant.client.client_name}} is requesting:
<strong>{{ grant.request.scope }}</strong>
</p>

<form action="" method="post">
  <label>
    <input type="checkbox" name="confirm">
    <span>Consent?</span>
  </label>
  {% if not user %}
  <p>You haven't logged in. Log in with:</p>
  <div>
    <input type="text" name="username">
  </div>
  {% endif %}
  <br>
  <button>Submit</button>
</form>

lesite/templates/index.html
{%if user:%}
<a href="{{url_for('auth.logout')}}" title="Log out of the system">Logout</a>
<hr />
<div>
  <h3>User Details</h3>
  <p>{{user}}</p>
</div>

<div>
  <h3>Clients</h3>
  {%for client in clients%}
  <p>{{client.client_info|tojson}}</p>
  <p>{{client.client_metadata|tojson}}</p>
  <hr />
  {%endfor%}
</div>
<a href="{{url_for('index.add_client')}}" title="Add a new client">
  Add client
</a>
{%else:%}
<a href="{{url_for('auth.login')}}" title="Log in to the system">Login</a>
{%endif%}

lesite/templates/login.html
<form method="POST" action="{{url_for('auth.login', next_url=next_url)}}">
  <label for="username">Username</label>
  <input type="text" id="username" name="username" required="required" />

  <br />

  <label for="password">Password</label>
  <input type="password" id="password" name="password" required="required" />

  <br />

  <input type="submit" value="Login" />
</form>